### ISSUE TITLE
Core -> Route and Resource Loading: Handle runtime compilation errors

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#74]
See https://github.com/BeaconCMS/beacon/pull/35#issuecomment-1264392147 and https://github.com/BeaconCMS/beacon/pull/30#discussion_r1046000258 for more context.

Validate templates as they're saved or updated as suggested by @TheFirstAvenger: "start with trying to catch these bad templates when they are being saved initially, as that gets the feedback to the right person at the right time. Maybe we can start with a changeset validation"

**Comment by leandrocp** [comment]
Hey @AZholtkevych I've assigned to myself just to reserve the issue because @alexandrexaviersm is working on it so we can make it to v0.1 ok?

**Comment by AZholtkevych** [comment]
@leandrocp that's all good. Thanks a lot
